package procuradoria.map;
// Generated Mar 11, 2016 1:10:52 AM by Hibernate Tools 3.6.0



/**
 * UzatinvFf generated by hbm2java
 */
public class UzatinvFf  implements java.io.Serializable {


     private UzatinvFfId id;
     private Uzatfunci uzatfunci;
     private Uzatfase uzatfase;
     private String uzatinvolFfFIn;
     private String uzatinvolFfFOut;

    public UzatinvFf() {
        this.id = new UzatinvFfId();
        this.uzatfase = new Uzatfase();
        this.uzatfunci = new Uzatfunci();
    }

	
    public UzatinvFf(UzatinvFfId id, Uzatfunci uzatfunci, Uzatfase uzatfase) {
        this.id = id;
        this.uzatfunci = uzatfunci;
        this.uzatfase = uzatfase;
    }
    public UzatinvFf(UzatinvFfId id, Uzatfunci uzatfunci, Uzatfase uzatfase, String uzatinvolFfFIn, String uzatinvolFfFOut) {
       this.id = id;
       this.uzatfunci = uzatfunci;
       this.uzatfase = uzatfase;
       this.uzatinvolFfFIn = uzatinvolFfFIn;
       this.uzatinvolFfFOut = uzatinvolFfFOut;
    }
   
    public UzatinvFfId getId() {
        return this.id;
    }
    
    public void setId(UzatinvFfId id) {
        this.id = id;
    }
    public Uzatfunci getUzatfunci() {
        return this.uzatfunci;
    }
    
    public void setUzatfunci(Uzatfunci uzatfunci) {
        this.uzatfunci = uzatfunci;
    }
    public Uzatfase getUzatfase() {
        return this.uzatfase;
    }
    
    public void setUzatfase(Uzatfase uzatfase) {
        this.uzatfase = uzatfase;
    }
    public String getUzatinvolFfFIn() {
        return this.uzatinvolFfFIn;
    }
    
    public void setUzatinvolFfFIn(String uzatinvolFfFIn) {
        this.uzatinvolFfFIn = uzatinvolFfFIn;
    }
    public String getUzatinvolFfFOut() {
        return this.uzatinvolFfFOut;
    }
    
    public void setUzatinvolFfFOut(String uzatinvolFfFOut) {
        this.uzatinvolFfFOut = uzatinvolFfFOut;
    }




}


