package procuradoria.map;
// Generated Mar 28, 2016 5:02:18 PM by Hibernate Tools 3.6.0


import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Blob;

/**
 * Uzatdocs generated by hbm2java
 */
public class Uzatdocs  implements java.io.Serializable {


     private UzatdocsId id;
     private Uzatfase uzatfase;
     private String uzatdocsCasilla;
     private String uzatdocsFecha;
     private String uzatdocsCompromiso;
     private Blob uzatdocsArchivo;
     private BigDecimal uzatfuncionarioId;
     
     private InputStream uzatdocsPdf;
     private Long uzatdocsPdfSize;

    public Uzatdocs() {
        this.id = new UzatdocsId();
        this.uzatfase = new Uzatfase();
        this.uzatfuncionarioId = new BigDecimal(BigInteger.ONE);
    }

	
    public Uzatdocs(UzatdocsId id, Uzatfase uzatfase) {
        this.id = id;
        this.uzatfase = uzatfase;
    }
    public Uzatdocs(UzatdocsId id, Uzatfase uzatfase, String uzatdocsCasilla, String uzatdocsFecha, String uzatdocsCompromiso, Blob uzatdocsArchivo, BigDecimal uzatfuncionarioId) {
       this.id = id;
       this.uzatfase = uzatfase;
       this.uzatdocsCasilla = uzatdocsCasilla;
       this.uzatdocsFecha = uzatdocsFecha;
       this.uzatdocsCompromiso = uzatdocsCompromiso;
       this.uzatdocsArchivo = uzatdocsArchivo;
       this.uzatfuncionarioId = uzatfuncionarioId;
    }
   
    public UzatdocsId getId() {
        return this.id;
    }
    
    public void setId(UzatdocsId id) {
        this.id = id;
    }
    public Uzatfase getUzatfase() {
        return this.uzatfase;
    }
    
    public void setUzatfase(Uzatfase uzatfase) {
        this.uzatfase = uzatfase;
    }
    public String getUzatdocsCasilla() {
        return this.uzatdocsCasilla;
    }
    
    public void setUzatdocsCasilla(String uzatdocsCasilla) {
        this.uzatdocsCasilla = uzatdocsCasilla;
    }
    public String getUzatdocsFecha() {
        return this.uzatdocsFecha;
    }
    
    public void setUzatdocsFecha(String uzatdocsFecha) {
        this.uzatdocsFecha = uzatdocsFecha;
    }
    public String getUzatdocsCompromiso() {
        return this.uzatdocsCompromiso;
    }
    
    public void setUzatdocsCompromiso(String uzatdocsCompromiso) {
        this.uzatdocsCompromiso = uzatdocsCompromiso;
    }
    public Blob getUzatdocsArchivo() {
        return this.uzatdocsArchivo;
    }
    
    public void setUzatdocsArchivo(Blob uzatdocsArchivo) {
        this.uzatdocsArchivo = uzatdocsArchivo;
    }
    public BigDecimal getUzatfuncionarioId() {
        return this.uzatfuncionarioId;
    }
    
    public void setUzatfuncionarioId(BigDecimal uzatfuncionarioId) {
        this.uzatfuncionarioId = uzatfuncionarioId;
    }

    public InputStream getUzatdocsPdf() {
        return uzatdocsPdf;
    }

    public void setUzatdocsPdf(InputStream uzatdocsPdf) {
        this.uzatdocsPdf = uzatdocsPdf;
    }

    public Long getUzatdocsPdfSize() {
        return uzatdocsPdfSize;
    }

    public void setUzatdocsPdfSize(Long uzatdocsPdfSize) {
        this.uzatdocsPdfSize = uzatdocsPdfSize;
    }




}


