package procuradoria.map;
// Generated Mar 1, 2016 11:18:31 AM by Hibernate Tools 3.6.0



/**
 * Uzatcomt generated by hbm2java
 */
public class Uzatcomt  implements java.io.Serializable {


     private UzatcomtId id;
     private Uzatfase uzatfase;
     private String uzatcomtDescripcion;
     private String uzatcomtFecha;

    public Uzatcomt() {
        this.id = new UzatcomtId();
        this.uzatfase = new Uzatfase();
    }

	
    public Uzatcomt(UzatcomtId id, Uzatfase uzatfase) {
        this.id = id;
        this.uzatfase = uzatfase;
    }
    public Uzatcomt(UzatcomtId id, Uzatfase uzatfase, String uzatcomtDescripcion, String uzatcomtFecha) {
       this.id = id;
       this.uzatfase = uzatfase;
       this.uzatcomtDescripcion = uzatcomtDescripcion;
       this.uzatcomtFecha = uzatcomtFecha;
    }
   
    public UzatcomtId getId() {
        return this.id;
    }
    
    public void setId(UzatcomtId id) {
        this.id = id;
    }
    public Uzatfase getUzatfase() {
        return this.uzatfase;
    }
    
    public void setUzatfase(Uzatfase uzatfase) {
        this.uzatfase = uzatfase;
    }
    public String getUzatcomtDescripcion() {
        return this.uzatcomtDescripcion;
    }
    
    public void setUzatcomtDescripcion(String uzatcomtDescripcion) {
        this.uzatcomtDescripcion = uzatcomtDescripcion;
    }
    public String getUzatcomtFecha() {
        return this.uzatcomtFecha;
    }
    
    public void setUzatcomtFecha(String uzatcomtFecha) {
        this.uzatcomtFecha = uzatcomtFecha;
    }




}


