package procuradoria.map;
// Generated Feb 3, 2016 11:47:39 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UzatinvCa generated by hbm2java
 */
public class UzatinvCa  implements java.io.Serializable {


     private UzatinvCaId id;
     private Uzatcaso uzatcaso;
     private Uzatactor uzatactor;
     private Date uzatinvolCa;

    public UzatinvCa() {
    }

	
    public UzatinvCa(UzatinvCaId id, Uzatcaso uzatcaso, Uzatactor uzatactor) {
        this.id = id;
        this.uzatcaso = uzatcaso;
        this.uzatactor = uzatactor;
    }
    public UzatinvCa(UzatinvCaId id, Uzatcaso uzatcaso, Uzatactor uzatactor, Date uzatinvolCa) {
       this.id = id;
       this.uzatcaso = uzatcaso;
       this.uzatactor = uzatactor;
       this.uzatinvolCa = uzatinvolCa;
    }
   
    public UzatinvCaId getId() {
        return this.id;
    }
    
    public void setId(UzatinvCaId id) {
        this.id = id;
    }
    public Uzatcaso getUzatcaso() {
        return this.uzatcaso;
    }
    
    public void setUzatcaso(Uzatcaso uzatcaso) {
        this.uzatcaso = uzatcaso;
    }
    public Uzatactor getUzatactor() {
        return this.uzatactor;
    }
    
    public void setUzatactor(Uzatactor uzatactor) {
        this.uzatactor = uzatactor;
    }
    public Date getUzatinvolCa() {
        return this.uzatinvolCa;
    }
    
    public void setUzatinvolCa(Date uzatinvolCa) {
        this.uzatinvolCa = uzatinvolCa;
    }




}


