package procuradoria.map;
// Generated Mar 25, 2016 3:25:02 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UzatinvFfId generated by hbm2java
 */
public class UzatinvFfId  implements java.io.Serializable {


     private BigDecimal uzatfuncionarioId;
     private BigDecimal uzatcasoId;
     private BigDecimal uzatfaseId;

    public UzatinvFfId() {
        this.uzatcasoId = new BigDecimal(BigInteger.ONE);
        this.uzatfaseId = new BigDecimal(BigInteger.ONE);
        this.uzatfuncionarioId = new BigDecimal(BigInteger.ONE);
    }

    public UzatinvFfId(BigDecimal uzatfuncionarioId, BigDecimal uzatcasoId, BigDecimal uzatfaseId) {
       this.uzatfuncionarioId = uzatfuncionarioId;
       this.uzatcasoId = uzatcasoId;
       this.uzatfaseId = uzatfaseId;
    }
   
    public BigDecimal getUzatfuncionarioId() {
        return this.uzatfuncionarioId;
    }
    
    public void setUzatfuncionarioId(BigDecimal uzatfuncionarioId) {
        this.uzatfuncionarioId = uzatfuncionarioId;
    }
    public BigDecimal getUzatcasoId() {
        return this.uzatcasoId;
    }
    
    public void setUzatcasoId(BigDecimal uzatcasoId) {
        this.uzatcasoId = uzatcasoId;
    }
    public BigDecimal getUzatfaseId() {
        return this.uzatfaseId;
    }
    
    public void setUzatfaseId(BigDecimal uzatfaseId) {
        this.uzatfaseId = uzatfaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UzatinvFfId) ) return false;
		 UzatinvFfId castOther = ( UzatinvFfId ) other; 
         
		 return ( (this.getUzatfuncionarioId()==castOther.getUzatfuncionarioId()) || ( this.getUzatfuncionarioId()!=null && castOther.getUzatfuncionarioId()!=null && this.getUzatfuncionarioId().equals(castOther.getUzatfuncionarioId()) ) )
 && ( (this.getUzatcasoId()==castOther.getUzatcasoId()) || ( this.getUzatcasoId()!=null && castOther.getUzatcasoId()!=null && this.getUzatcasoId().equals(castOther.getUzatcasoId()) ) )
 && ( (this.getUzatfaseId()==castOther.getUzatfaseId()) || ( this.getUzatfaseId()!=null && castOther.getUzatfaseId()!=null && this.getUzatfaseId().equals(castOther.getUzatfaseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUzatfuncionarioId() == null ? 0 : this.getUzatfuncionarioId().hashCode() );
         result = 37 * result + ( getUzatcasoId() == null ? 0 : this.getUzatcasoId().hashCode() );
         result = 37 * result + ( getUzatfaseId() == null ? 0 : this.getUzatfaseId().hashCode() );
         return result;
   }   


}


