package procuradoria.map;
// Generated Feb 3, 2016 11:47:39 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Uzatcomt generated by hbm2java
 */
public class Uzatcomt  implements java.io.Serializable {


     private UzatcomtId id;
     private Uzatfase uzatfase;
     private String uzatcomtDescripcion;
     private Date uzatcomtFecha;

    public Uzatcomt() {
    }

	
    public Uzatcomt(UzatcomtId id, Uzatfase uzatfase) {
        this.id = id;
        this.uzatfase = uzatfase;
    }
    public Uzatcomt(UzatcomtId id, Uzatfase uzatfase, String uzatcomtDescripcion, Date uzatcomtFecha) {
       this.id = id;
       this.uzatfase = uzatfase;
       this.uzatcomtDescripcion = uzatcomtDescripcion;
       this.uzatcomtFecha = uzatcomtFecha;
    }
   
    public UzatcomtId getId() {
        return this.id;
    }
    
    public void setId(UzatcomtId id) {
        this.id = id;
    }
    public Uzatfase getUzatfase() {
        return this.uzatfase;
    }
    
    public void setUzatfase(Uzatfase uzatfase) {
        this.uzatfase = uzatfase;
    }
    public String getUzatcomtDescripcion() {
        return this.uzatcomtDescripcion;
    }
    
    public void setUzatcomtDescripcion(String uzatcomtDescripcion) {
        this.uzatcomtDescripcion = uzatcomtDescripcion;
    }
    public Date getUzatcomtFecha() {
        return this.uzatcomtFecha;
    }
    
    public void setUzatcomtFecha(Date uzatcomtFecha) {
        this.uzatcomtFecha = uzatcomtFecha;
    }




}


