package procuradoria.map;
// Generated Feb 3, 2016 11:47:39 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Uzatmateri generated by hbm2java
 */
public class Uzatmateri  implements java.io.Serializable {


     private BigDecimal uzatmateriaId;
     private String uzatmateriaDescripcion;
     private Set uzatjudis = new HashSet(0);

    public Uzatmateri() {
    }

	
    public Uzatmateri(BigDecimal uzatmateriaId) {
        this.uzatmateriaId = uzatmateriaId;
    }
    public Uzatmateri(BigDecimal uzatmateriaId, String uzatmateriaDescripcion, Set uzatjudis) {
       this.uzatmateriaId = uzatmateriaId;
       this.uzatmateriaDescripcion = uzatmateriaDescripcion;
       this.uzatjudis = uzatjudis;
    }
   
    public BigDecimal getUzatmateriaId() {
        return this.uzatmateriaId;
    }
    
    public void setUzatmateriaId(BigDecimal uzatmateriaId) {
        this.uzatmateriaId = uzatmateriaId;
    }
    public String getUzatmateriaDescripcion() {
        return this.uzatmateriaDescripcion;
    }
    
    public void setUzatmateriaDescripcion(String uzatmateriaDescripcion) {
        this.uzatmateriaDescripcion = uzatmateriaDescripcion;
    }
    public Set getUzatjudis() {
        return this.uzatjudis;
    }
    
    public void setUzatjudis(Set uzatjudis) {
        this.uzatjudis = uzatjudis;
    }




}


