package procuradoria.map;
// Generated Feb 5, 2016 12:46:40 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UzatasignId generated by hbm2java
 */
public class UzatasignId  implements java.io.Serializable {


     private BigDecimal uzatfuncionarioId;
     private BigDecimal uzatcasoId;

    public UzatasignId() {
    }

    public UzatasignId(BigDecimal uzatfuncionarioId, BigDecimal uzatcasoId) {
       this.uzatfuncionarioId = uzatfuncionarioId;
       this.uzatcasoId = uzatcasoId;
    }
   
    public BigDecimal getUzatfuncionarioId() {
        return this.uzatfuncionarioId;
    }
    
    public void setUzatfuncionarioId(BigDecimal uzatfuncionarioId) {
        this.uzatfuncionarioId = uzatfuncionarioId;
    }
    public BigDecimal getUzatcasoId() {
        return this.uzatcasoId;
    }
    
    public void setUzatcasoId(BigDecimal uzatcasoId) {
        this.uzatcasoId = uzatcasoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UzatasignId) ) return false;
		 UzatasignId castOther = ( UzatasignId ) other; 
         
		 return ( (this.getUzatfuncionarioId()==castOther.getUzatfuncionarioId()) || ( this.getUzatfuncionarioId()!=null && castOther.getUzatfuncionarioId()!=null && this.getUzatfuncionarioId().equals(castOther.getUzatfuncionarioId()) ) )
 && ( (this.getUzatcasoId()==castOther.getUzatcasoId()) || ( this.getUzatcasoId()!=null && castOther.getUzatcasoId()!=null && this.getUzatcasoId().equals(castOther.getUzatcasoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUzatfuncionarioId() == null ? 0 : this.getUzatfuncionarioId().hashCode() );
         result = 37 * result + ( getUzatcasoId() == null ? 0 : this.getUzatcasoId().hashCode() );
         return result;
   }   


}


