package procuradoria.map;
// Generated 07/04/2016 02:59:05 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UzatinvCaId generated by hbm2java
 */
public class UzatinvCaId implements java.io.Serializable {

    private BigDecimal uzatactorId;
    private BigDecimal uzatcasoId;

    public UzatinvCaId() {
        this.uzatactorId = new BigDecimal(BigInteger.ZERO);
        this.uzatcasoId = new BigDecimal(BigInteger.ZERO);
    }

    public UzatinvCaId(BigDecimal uzatactorId, BigDecimal uzatcasoId) {
        this.uzatactorId = uzatactorId;
        this.uzatcasoId = uzatcasoId;
    }

    public BigDecimal getUzatactorId() {
        return this.uzatactorId;
    }

    public void setUzatactorId(BigDecimal uzatactorId) {
        this.uzatactorId = uzatactorId;
    }

    public BigDecimal getUzatcasoId() {
        return this.uzatcasoId;
    }

    public void setUzatcasoId(BigDecimal uzatcasoId) {
        this.uzatcasoId = uzatcasoId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UzatinvCaId)) {
            return false;
        }
        UzatinvCaId castOther = (UzatinvCaId) other;

        return ((this.getUzatactorId() == castOther.getUzatactorId()) || (this.getUzatactorId() != null && castOther.getUzatactorId() != null && this.getUzatactorId().equals(castOther.getUzatactorId())))
                && ((this.getUzatcasoId() == castOther.getUzatcasoId()) || (this.getUzatcasoId() != null && castOther.getUzatcasoId() != null && this.getUzatcasoId().equals(castOther.getUzatcasoId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUzatactorId() == null ? 0 : this.getUzatactorId().hashCode());
        result = 37 * result + (getUzatcasoId() == null ? 0 : this.getUzatcasoId().hashCode());
        return result;
    }

}
