package procuradoria.map;
// Generated Mar 28, 2016 5:02:18 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UzatrolId generated by hbm2java
 */
public class UzatrolId  implements java.io.Serializable {


     private BigDecimal uzattiporolId;
     private BigDecimal uzatfuncionarioId;
     private BigDecimal uzatrolId;

    public UzatrolId() {
        this.uzatfuncionarioId = new BigDecimal(BigInteger.ONE);
        this.uzatrolId = new BigDecimal(BigInteger.ONE);
        this.uzattiporolId = new BigDecimal(BigInteger.ONE);
    }

    public UzatrolId(BigDecimal uzattiporolId, BigDecimal uzatfuncionarioId, BigDecimal uzatrolId) {
       this.uzattiporolId = uzattiporolId;
       this.uzatfuncionarioId = uzatfuncionarioId;
       this.uzatrolId = uzatrolId;
    }
   
    public BigDecimal getUzattiporolId() {
        return this.uzattiporolId;
    }
    
    public void setUzattiporolId(BigDecimal uzattiporolId) {
        this.uzattiporolId = uzattiporolId;
    }
    public BigDecimal getUzatfuncionarioId() {
        return this.uzatfuncionarioId;
    }
    
    public void setUzatfuncionarioId(BigDecimal uzatfuncionarioId) {
        this.uzatfuncionarioId = uzatfuncionarioId;
    }
    public BigDecimal getUzatrolId() {
        return this.uzatrolId;
    }
    
    public void setUzatrolId(BigDecimal uzatrolId) {
        this.uzatrolId = uzatrolId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UzatrolId) ) return false;
		 UzatrolId castOther = ( UzatrolId ) other; 
         
		 return ( (this.getUzattiporolId()==castOther.getUzattiporolId()) || ( this.getUzattiporolId()!=null && castOther.getUzattiporolId()!=null && this.getUzattiporolId().equals(castOther.getUzattiporolId()) ) )
 && ( (this.getUzatfuncionarioId()==castOther.getUzatfuncionarioId()) || ( this.getUzatfuncionarioId()!=null && castOther.getUzatfuncionarioId()!=null && this.getUzatfuncionarioId().equals(castOther.getUzatfuncionarioId()) ) )
 && ( (this.getUzatrolId()==castOther.getUzatrolId()) || ( this.getUzatrolId()!=null && castOther.getUzatrolId()!=null && this.getUzatrolId().equals(castOther.getUzatrolId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUzattiporolId() == null ? 0 : this.getUzattiporolId().hashCode() );
         result = 37 * result + ( getUzatfuncionarioId() == null ? 0 : this.getUzatfuncionarioId().hashCode() );
         result = 37 * result + ( getUzatrolId() == null ? 0 : this.getUzatrolId().hashCode() );
         return result;
   }   


}


