package procuradoria.map;
// Generated Mar 25, 2016 3:25:02 PM by Hibernate Tools 3.6.0



/**
 * UzatinvCa generated by hbm2java
 */
public class UzatinvCa  implements java.io.Serializable {


     private UzatinvCaId id;
     private Uzatcaso uzatcaso;
     private Uzatactor uzatactor;
     private String uzatinvolCa;
     private String uzatinvTipo;

    public UzatinvCa() {
        this.id = new UzatinvCaId();
        this.uzatactor = new Uzatactor();
        this.uzatcaso = new Uzatcaso();
    }

	
    public UzatinvCa(UzatinvCaId id, Uzatcaso uzatcaso, Uzatactor uzatactor) {
        this.id = id;
        this.uzatcaso = uzatcaso;
        this.uzatactor = uzatactor;
    }
    public UzatinvCa(UzatinvCaId id, Uzatcaso uzatcaso, Uzatactor uzatactor, String uzatinvolCa, String uzatinvTipo) {
       this.id = id;
       this.uzatcaso = uzatcaso;
       this.uzatactor = uzatactor;
       this.uzatinvolCa = uzatinvolCa;
       this.uzatinvTipo = uzatinvTipo;
    }
   
    public UzatinvCaId getId() {
        return this.id;
    }
    
    public void setId(UzatinvCaId id) {
        this.id = id;
    }
    public Uzatcaso getUzatcaso() {
        return this.uzatcaso;
    }
    
    public void setUzatcaso(Uzatcaso uzatcaso) {
        this.uzatcaso = uzatcaso;
    }
    public Uzatactor getUzatactor() {
        return this.uzatactor;
    }
    
    public void setUzatactor(Uzatactor uzatactor) {
        this.uzatactor = uzatactor;
    }
    public String getUzatinvolCa() {
        return this.uzatinvolCa;
    }
    
    public void setUzatinvolCa(String uzatinvolCa) {
        this.uzatinvolCa = uzatinvolCa;
    }
    public String getUzatinvTipo() {
        return this.uzatinvTipo;
    }
    
    public void setUzatinvTipo(String uzatinvTipo) {
        this.uzatinvTipo = uzatinvTipo;
    }




}


