package procuradoria.map;
// Generated Mar 28, 2016 5:02:18 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * Uzatasign generated by hbm2java
 */
public class Uzatasign  implements java.io.Serializable {


     private UzatasignId id;
     private Uzatcaso uzatcaso;
     private Uzatfunci uzatfunci;
     private BigDecimal uzatasignarId;
     private String uzatasignarFechaIn;
     private String uzatasignarFechaOut;
     private String uzatasignarMotivo;
     private BigDecimal uzatasignarFlag;
     
     private Uzatfase UltimaFaseActual;

    public Uzatasign() {
        this.id = new UzatasignId();
        this.uzatcaso = new Uzatcaso();
        this.uzatfunci = new Uzatfunci(); 
        this.uzatasignarId = new BigDecimal(BigInteger.ONE);
        this.uzatasignarFlag = new BigDecimal(BigInteger.ZERO);
        this.UltimaFaseActual = new Uzatfase();
    }

	
    public Uzatasign(UzatasignId id, Uzatcaso uzatcaso, Uzatfunci uzatfunci) {
        this.id = id;
        this.uzatcaso = uzatcaso;
        this.uzatfunci = uzatfunci;
    }
    public Uzatasign(UzatasignId id, Uzatcaso uzatcaso, Uzatfunci uzatfunci, BigDecimal uzatasignarId, String uzatasignarFechaIn, String uzatasignarFechaOut, String uzatasignarMotivo, BigDecimal uzatasignarFlag) {
       this.id = id;
       this.uzatcaso = uzatcaso;
       this.uzatfunci = uzatfunci;
       this.uzatasignarId = uzatasignarId;
       this.uzatasignarFechaIn = uzatasignarFechaIn;
       this.uzatasignarFechaOut = uzatasignarFechaOut;
       this.uzatasignarMotivo = uzatasignarMotivo;
       this.uzatasignarFlag = uzatasignarFlag;
    }
   
    public UzatasignId getId() {
        return this.id;
    }
    
    public void setId(UzatasignId id) {
        this.id = id;
    }
    public Uzatcaso getUzatcaso() {
        return this.uzatcaso;
    }
    
    public void setUzatcaso(Uzatcaso uzatcaso) {
        this.uzatcaso = uzatcaso;
    }
    public Uzatfunci getUzatfunci() {
        return this.uzatfunci;
    }
    
    public void setUzatfunci(Uzatfunci uzatfunci) {
        this.uzatfunci = uzatfunci;
    }
    public BigDecimal getUzatasignarId() {
        return this.uzatasignarId;
    }
    
    public void setUzatasignarId(BigDecimal uzatasignarId) {
        this.uzatasignarId = uzatasignarId;
    }
    public String getUzatasignarFechaIn() {
        return this.uzatasignarFechaIn;
    }
    
    public void setUzatasignarFechaIn(String uzatasignarFechaIn) {
        this.uzatasignarFechaIn = uzatasignarFechaIn;
    }
    public String getUzatasignarFechaOut() {
        return this.uzatasignarFechaOut;
    }
    
    public void setUzatasignarFechaOut(String uzatasignarFechaOut) {
        this.uzatasignarFechaOut = uzatasignarFechaOut;
    }
    public String getUzatasignarMotivo() {
        return this.uzatasignarMotivo;
    }
    
    public void setUzatasignarMotivo(String uzatasignarMotivo) {
        this.uzatasignarMotivo = uzatasignarMotivo;
    }
    public BigDecimal getUzatasignarFlag() {
        return this.uzatasignarFlag;
    }
    
    public void setUzatasignarFlag(BigDecimal uzatasignarFlag) {
        this.uzatasignarFlag = uzatasignarFlag;
    }

    public Uzatfase getUltimaFaseActual() {
        return UltimaFaseActual;
    }

    public void setUltimaFaseActual(Uzatfase UltimaFaseActual) {
        this.UltimaFaseActual = UltimaFaseActual;
    }




}


