package procuradoria.map;
// Generated Feb 5, 2016 12:46:40 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Uzatjudi generated by hbm2java
 */
public class Uzatjudi  implements java.io.Serializable {


     private UzatjudiId id;
     private Uzatmateri uzatmateri;
     private String uzatjudiDescripcion;
     private Set uzatcasos = new HashSet(0);

    public Uzatjudi() {
    }

	
    public Uzatjudi(UzatjudiId id, Uzatmateri uzatmateri) {
        this.id = id;
        this.uzatmateri = uzatmateri;
    }
    public Uzatjudi(UzatjudiId id, Uzatmateri uzatmateri, String uzatjudiDescripcion, Set uzatcasos) {
       this.id = id;
       this.uzatmateri = uzatmateri;
       this.uzatjudiDescripcion = uzatjudiDescripcion;
       this.uzatcasos = uzatcasos;
    }
   
    public UzatjudiId getId() {
        return this.id;
    }
    
    public void setId(UzatjudiId id) {
        this.id = id;
    }
    public Uzatmateri getUzatmateri() {
        return this.uzatmateri;
    }
    
    public void setUzatmateri(Uzatmateri uzatmateri) {
        this.uzatmateri = uzatmateri;
    }
    public String getUzatjudiDescripcion() {
        return this.uzatjudiDescripcion;
    }
    
    public void setUzatjudiDescripcion(String uzatjudiDescripcion) {
        this.uzatjudiDescripcion = uzatjudiDescripcion;
    }
    public Set getUzatcasos() {
        return this.uzatcasos;
    }
    
    public void setUzatcasos(Set uzatcasos) {
        this.uzatcasos = uzatcasos;
    }




}


