package procuradoria.map;
// Generated Feb 3, 2016 11:47:39 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * Uzatrol generated by hbm2java
 */
public class Uzatrol  implements java.io.Serializable {


     private UzatrolId id;
     private Uzatfunci uzatfunci;
     private Uzattrol uzattrol;
     private String uzatrolCod;
     private Date uzatrolFechaIn;
     private Date uzatrolFechaOut;
     private BigDecimal uzatrolFlag;

    public Uzatrol() {
    }

	
    public Uzatrol(UzatrolId id, Uzatfunci uzatfunci, Uzattrol uzattrol) {
        this.id = id;
        this.uzatfunci = uzatfunci;
        this.uzattrol = uzattrol;
    }
    public Uzatrol(UzatrolId id, Uzatfunci uzatfunci, Uzattrol uzattrol, String uzatrolCod, Date uzatrolFechaIn, Date uzatrolFechaOut, BigDecimal uzatrolFlag) {
       this.id = id;
       this.uzatfunci = uzatfunci;
       this.uzattrol = uzattrol;
       this.uzatrolCod = uzatrolCod;
       this.uzatrolFechaIn = uzatrolFechaIn;
       this.uzatrolFechaOut = uzatrolFechaOut;
       this.uzatrolFlag = uzatrolFlag;
    }
   
    public UzatrolId getId() {
        return this.id;
    }
    
    public void setId(UzatrolId id) {
        this.id = id;
    }
    public Uzatfunci getUzatfunci() {
        return this.uzatfunci;
    }
    
    public void setUzatfunci(Uzatfunci uzatfunci) {
        this.uzatfunci = uzatfunci;
    }
    public Uzattrol getUzattrol() {
        return this.uzattrol;
    }
    
    public void setUzattrol(Uzattrol uzattrol) {
        this.uzattrol = uzattrol;
    }
    public String getUzatrolCod() {
        return this.uzatrolCod;
    }
    
    public void setUzatrolCod(String uzatrolCod) {
        this.uzatrolCod = uzatrolCod;
    }
    public Date getUzatrolFechaIn() {
        return this.uzatrolFechaIn;
    }
    
    public void setUzatrolFechaIn(Date uzatrolFechaIn) {
        this.uzatrolFechaIn = uzatrolFechaIn;
    }
    public Date getUzatrolFechaOut() {
        return this.uzatrolFechaOut;
    }
    
    public void setUzatrolFechaOut(Date uzatrolFechaOut) {
        this.uzatrolFechaOut = uzatrolFechaOut;
    }
    public BigDecimal getUzatrolFlag() {
        return this.uzatrolFlag;
    }
    
    public void setUzatrolFlag(BigDecimal uzatrolFlag) {
        this.uzatrolFlag = uzatrolFlag;
    }




}


