package procuradoria.map;
// Generated 07/04/2016 02:59:05 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UzatcitaId generated by hbm2java
 */
public class UzatcitaId implements java.io.Serializable {

    private BigDecimal uzatcasoId;
    private BigDecimal uzatfaseId;
    private BigDecimal uzatcitaId;

    public UzatcitaId() {
        this.uzatcasoId = new BigDecimal(BigInteger.ZERO);
        this.uzatfaseId = new BigDecimal(BigInteger.ZERO);
        this.uzatcitaId = new BigDecimal(BigInteger.ZERO);
    }

    public UzatcitaId(BigDecimal uzatcasoId, BigDecimal uzatfaseId, BigDecimal uzatcitaId) {
        this.uzatcasoId = uzatcasoId;
        this.uzatfaseId = uzatfaseId;
        this.uzatcitaId = uzatcitaId;
    }

    public BigDecimal getUzatcasoId() {
        return this.uzatcasoId;
    }

    public void setUzatcasoId(BigDecimal uzatcasoId) {
        this.uzatcasoId = uzatcasoId;
    }

    public BigDecimal getUzatfaseId() {
        return this.uzatfaseId;
    }

    public void setUzatfaseId(BigDecimal uzatfaseId) {
        this.uzatfaseId = uzatfaseId;
    }

    public BigDecimal getUzatcitaId() {
        return this.uzatcitaId;
    }

    public void setUzatcitaId(BigDecimal uzatcitaId) {
        this.uzatcitaId = uzatcitaId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UzatcitaId)) {
            return false;
        }
        UzatcitaId castOther = (UzatcitaId) other;

        return ((this.getUzatcasoId() == castOther.getUzatcasoId()) || (this.getUzatcasoId() != null && castOther.getUzatcasoId() != null && this.getUzatcasoId().equals(castOther.getUzatcasoId())))
                && ((this.getUzatfaseId() == castOther.getUzatfaseId()) || (this.getUzatfaseId() != null && castOther.getUzatfaseId() != null && this.getUzatfaseId().equals(castOther.getUzatfaseId())))
                && ((this.getUzatcitaId() == castOther.getUzatcitaId()) || (this.getUzatcitaId() != null && castOther.getUzatcitaId() != null && this.getUzatcitaId().equals(castOther.getUzatcitaId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUzatcasoId() == null ? 0 : this.getUzatcasoId().hashCode());
        result = 37 * result + (getUzatfaseId() == null ? 0 : this.getUzatfaseId().hashCode());
        result = 37 * result + (getUzatcitaId() == null ? 0 : this.getUzatcitaId().hashCode());
        return result;
    }

}
