package procuradoria.map;
// Generated Mar 11, 2016 1:10:52 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;

/**
 * Uzatrol generated by hbm2java
 */
public class Uzatrol implements java.io.Serializable {

    private UzatrolId id;
    private Uzatfunci uzatfunci;
    private Uzattrol uzattrol;
    private String uzatrolCod;
    private String uzatrolFechaIn;
    private String uzatrolFechaOut;
    private BigDecimal uzatrolFlag;

    public Uzatrol() {
        this.id = new UzatrolId();
        this.uzatfunci = new Uzatfunci();
        this.uzattrol = new Uzattrol();
    }

    public Uzatrol(UzatrolId id, Uzatfunci uzatfunci, Uzattrol uzattrol) {
        this.id = id;
        this.uzatfunci = uzatfunci;
        this.uzattrol = uzattrol;
    }

    public Uzatrol(UzatrolId id, Uzatfunci uzatfunci, Uzattrol uzattrol, String uzatrolCod, String uzatrolFechaIn, String uzatrolFechaOut, BigDecimal uzatrolFlag) {
        this.id = id;
        this.uzatfunci = uzatfunci;
        this.uzattrol = uzattrol;
        this.uzatrolCod = uzatrolCod;
        this.uzatrolFechaIn = uzatrolFechaIn;
        this.uzatrolFechaOut = uzatrolFechaOut;
        this.uzatrolFlag = uzatrolFlag;
    }

    public UzatrolId getId() {
        return this.id;
    }

    public void setId(UzatrolId id) {
        this.id = id;
    }

    public Uzatfunci getUzatfunci() {
        return this.uzatfunci;
    }

    public void setUzatfunci(Uzatfunci uzatfunci) {
        this.uzatfunci = uzatfunci;
    }

    public Uzattrol getUzattrol() {
        return this.uzattrol;
    }

    public void setUzattrol(Uzattrol uzattrol) {
        this.uzattrol = uzattrol;
    }

    public String getUzatrolCod() {
        return this.uzatrolCod;
    }

    public void setUzatrolCod(String uzatrolCod) {
        this.uzatrolCod = uzatrolCod;
    }

    public String getUzatrolFechaIn() {
        return this.uzatrolFechaIn;
    }

    public void setUzatrolFechaIn(String uzatrolFechaIn) {
        this.uzatrolFechaIn = uzatrolFechaIn;
    }

    public String getUzatrolFechaOut() {
        return this.uzatrolFechaOut;
    }

    public void setUzatrolFechaOut(String uzatrolFechaOut) {
        this.uzatrolFechaOut = uzatrolFechaOut;
    }

    public BigDecimal getUzatrolFlag() {
        return this.uzatrolFlag;
    }

    public void setUzatrolFlag(BigDecimal uzatrolFlag) {
        this.uzatrolFlag = uzatrolFlag;
    }

}
