package procuradoria.map;
// Generated 07/04/2016 02:59:05 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Uzatmateri generated by hbm2java
 */
public class Uzatmateri implements java.io.Serializable {

    private BigDecimal uzatmateriaId;
    private String uzatmateriaDescripcion;
    private String uzatmateriaFecha;
    private BigDecimal uzatfuncionarioId;
    private Set uzatjudis = new HashSet(0);

    public Uzatmateri() {
        this.uzatmateriaId = new BigDecimal(BigInteger.ZERO);
        this.uzatfuncionarioId = new BigDecimal(BigInteger.ZERO);
    }

    public Uzatmateri(BigDecimal uzatmateriaId) {
        this.uzatmateriaId = uzatmateriaId;
    }

    public Uzatmateri(BigDecimal uzatmateriaId, String uzatmateriaDescripcion, String uzatmateriaFecha, BigDecimal uzatfuncionarioId, Set uzatjudis) {
        this.uzatmateriaId = uzatmateriaId;
        this.uzatmateriaDescripcion = uzatmateriaDescripcion;
        this.uzatmateriaFecha = uzatmateriaFecha;
        this.uzatfuncionarioId = uzatfuncionarioId;
        this.uzatjudis = uzatjudis;
    }

    public BigDecimal getUzatmateriaId() {
        return this.uzatmateriaId;
    }

    public void setUzatmateriaId(BigDecimal uzatmateriaId) {
        this.uzatmateriaId = uzatmateriaId;
    }

    public String getUzatmateriaDescripcion() {
        return this.uzatmateriaDescripcion;
    }

    public void setUzatmateriaDescripcion(String uzatmateriaDescripcion) {
        this.uzatmateriaDescripcion = uzatmateriaDescripcion;
    }

    public String getUzatmateriaFecha() {
        return this.uzatmateriaFecha;
    }

    public void setUzatmateriaFecha(String uzatmateriaFecha) {
        this.uzatmateriaFecha = uzatmateriaFecha;
    }

    public BigDecimal getUzatfuncionarioId() {
        return this.uzatfuncionarioId;
    }

    public void setUzatfuncionarioId(BigDecimal uzatfuncionarioId) {
        this.uzatfuncionarioId = uzatfuncionarioId;
    }

    public Set getUzatjudis() {
        return this.uzatjudis;
    }

    public void setUzatjudis(Set uzatjudis) {
        this.uzatjudis = uzatjudis;
    }

}
