package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztactor generated by hbm2java
 */
public class Uztactor  implements java.io.Serializable {


     private BigDecimal uztactorId;
     private String uztactorNombres;
     private String uztactorApellidos;
     private String uztactorCedula;
     private String uztactorDireccion;
     private String uztactorMovil;
     private String uztactorEmail;
     private String uztactorInstitutcion;
     private BigDecimal uztactorTipo;
     private Set uztinvolCas = new HashSet(0);

    public Uztactor() {
    }

	
    public Uztactor(BigDecimal uztactorId) {
        this.uztactorId = uztactorId;
    }
    public Uztactor(BigDecimal uztactorId, String uztactorNombres, String uztactorApellidos, String uztactorCedula, String uztactorDireccion, String uztactorMovil, String uztactorEmail, String uztactorInstitutcion, BigDecimal uztactorTipo, Set uztinvolCas) {
       this.uztactorId = uztactorId;
       this.uztactorNombres = uztactorNombres;
       this.uztactorApellidos = uztactorApellidos;
       this.uztactorCedula = uztactorCedula;
       this.uztactorDireccion = uztactorDireccion;
       this.uztactorMovil = uztactorMovil;
       this.uztactorEmail = uztactorEmail;
       this.uztactorInstitutcion = uztactorInstitutcion;
       this.uztactorTipo = uztactorTipo;
       this.uztinvolCas = uztinvolCas;
    }
   
    public BigDecimal getUztactorId() {
        return this.uztactorId;
    }
    
    public void setUztactorId(BigDecimal uztactorId) {
        this.uztactorId = uztactorId;
    }
    public String getUztactorNombres() {
        return this.uztactorNombres;
    }
    
    public void setUztactorNombres(String uztactorNombres) {
        this.uztactorNombres = uztactorNombres;
    }
    public String getUztactorApellidos() {
        return this.uztactorApellidos;
    }
    
    public void setUztactorApellidos(String uztactorApellidos) {
        this.uztactorApellidos = uztactorApellidos;
    }
    public String getUztactorCedula() {
        return this.uztactorCedula;
    }
    
    public void setUztactorCedula(String uztactorCedula) {
        this.uztactorCedula = uztactorCedula;
    }
    public String getUztactorDireccion() {
        return this.uztactorDireccion;
    }
    
    public void setUztactorDireccion(String uztactorDireccion) {
        this.uztactorDireccion = uztactorDireccion;
    }
    public String getUztactorMovil() {
        return this.uztactorMovil;
    }
    
    public void setUztactorMovil(String uztactorMovil) {
        this.uztactorMovil = uztactorMovil;
    }
    public String getUztactorEmail() {
        return this.uztactorEmail;
    }
    
    public void setUztactorEmail(String uztactorEmail) {
        this.uztactorEmail = uztactorEmail;
    }
    public String getUztactorInstitutcion() {
        return this.uztactorInstitutcion;
    }
    
    public void setUztactorInstitutcion(String uztactorInstitutcion) {
        this.uztactorInstitutcion = uztactorInstitutcion;
    }
    public BigDecimal getUztactorTipo() {
        return this.uztactorTipo;
    }
    
    public void setUztactorTipo(BigDecimal uztactorTipo) {
        this.uztactorTipo = uztactorTipo;
    }
    public Set getUztinvolCas() {
        return this.uztinvolCas;
    }
    
    public void setUztinvolCas(Set uztinvolCas) {
        this.uztinvolCas = uztinvolCas;
    }




}


