package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UztasignarId generated by hbm2java
 */
public class UztasignarId  implements java.io.Serializable {


     private BigDecimal uztfuncionarioId;
     private BigDecimal uztcasoId;

    public UztasignarId() {
    }

    public UztasignarId(BigDecimal uztfuncionarioId, BigDecimal uztcasoId) {
       this.uztfuncionarioId = uztfuncionarioId;
       this.uztcasoId = uztcasoId;
    }
   
    public BigDecimal getUztfuncionarioId() {
        return this.uztfuncionarioId;
    }
    
    public void setUztfuncionarioId(BigDecimal uztfuncionarioId) {
        this.uztfuncionarioId = uztfuncionarioId;
    }
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztasignarId) ) return false;
		 UztasignarId castOther = ( UztasignarId ) other; 
         
		 return ( (this.getUztfuncionarioId()==castOther.getUztfuncionarioId()) || ( this.getUztfuncionarioId()!=null && castOther.getUztfuncionarioId()!=null && this.getUztfuncionarioId().equals(castOther.getUztfuncionarioId()) ) )
 && ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztfuncionarioId() == null ? 0 : this.getUztfuncionarioId().hashCode() );
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         return result;
   }   


}


