package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Uztasignar generated by hbm2java
 */
public class Uztasignar  implements java.io.Serializable {


     private UztasignarId id;
     private Uztcaso uztcaso;
     private Uztfuncionario uztfuncionario;
     private BigDecimal uztasignarId;
     private String uztasignarFechaIn;
     private String uztasignarFechaOut;
     private BigDecimal uztasignarFlag;
     private String uztasignarMotivo;

    public Uztasignar() {
        this.uztfuncionario = new Uztfuncionario();
        this.uztcaso = new Uztcaso();
    }

	
    public Uztasignar(UztasignarId id, Uztcaso uztcaso, Uztfuncionario uztfuncionario) {
        this.id = id;
        this.uztcaso = uztcaso;
        this.uztfuncionario = uztfuncionario;
    }
    public Uztasignar(UztasignarId id, Uztcaso uztcaso, Uztfuncionario uztfuncionario, BigDecimal uztasignarId, String uztasignarFechaIn, String uztasignarFechaOut, BigDecimal uztasignarFlag, String uztasignarMotivo) {
       this.id = id;
       this.uztcaso = uztcaso;
       this.uztfuncionario = uztfuncionario;
       this.uztasignarId = uztasignarId;
       this.uztasignarFechaIn = uztasignarFechaIn;
       this.uztasignarFechaOut = uztasignarFechaOut;
       this.uztasignarFlag = uztasignarFlag;
       this.uztasignarMotivo = uztasignarMotivo;
    }
   
    public UztasignarId getId() {
        return this.id;
    }
    
    public void setId(UztasignarId id) {
        this.id = id;
    }
    public Uztcaso getUztcaso() {
        return this.uztcaso;
    }
    
    public void setUztcaso(Uztcaso uztcaso) {
        this.uztcaso = uztcaso;
    }
    public Uztfuncionario getUztfuncionario() {
        return this.uztfuncionario;
    }
    
    public void setUztfuncionario(Uztfuncionario uztfuncionario) {
        this.uztfuncionario = uztfuncionario;
    }
    public BigDecimal getUztasignarId() {
        return this.uztasignarId;
    }
    
    public void setUztasignarId(BigDecimal uztasignarId) {
        this.uztasignarId = uztasignarId;
    }
    public String getUztasignarFechaIn() {
        return this.uztasignarFechaIn;
    }
    
    public void setUztasignarFechaIn(String uztasignarFechaIn) {
        this.uztasignarFechaIn = uztasignarFechaIn;
    }
    public String getUztasignarFechaOut() {
        return this.uztasignarFechaOut;
    }
    
    public void setUztasignarFechaOut(String uztasignarFechaOut) {
        this.uztasignarFechaOut = uztasignarFechaOut;
    }
    public BigDecimal getUztasignarFlag() {
        return this.uztasignarFlag;
    }
    
    public void setUztasignarFlag(BigDecimal uztasignarFlag) {
        this.uztasignarFlag = uztasignarFlag;
    }
    public String getUztasignarMotivo() {
        return this.uztasignarMotivo;
    }
    
    public void setUztasignarMotivo(String uztasignarMotivo) {
        this.uztasignarMotivo = uztasignarMotivo;
    }




}


