package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztcitaId generated by hbm2java
 */
public class UztcitaId  implements java.io.Serializable {


     private BigDecimal uztcasoId;
     private BigDecimal uztfaseId;
     private BigDecimal uztcitaId;

    public UztcitaId() {
        this.uztcasoId = new BigDecimal(BigInteger.ONE);
        this.uztcitaId = new BigDecimal(BigInteger.ONE);
        this.uztfaseId = new BigDecimal(BigInteger.ONE);
    }

    public UztcitaId(BigDecimal uztcasoId, BigDecimal uztfaseId, BigDecimal uztcitaId) {
       this.uztcasoId = uztcasoId;
       this.uztfaseId = uztfaseId;
       this.uztcitaId = uztcitaId;
    }
   
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }
    public BigDecimal getUztfaseId() {
        return this.uztfaseId;
    }
    
    public void setUztfaseId(BigDecimal uztfaseId) {
        this.uztfaseId = uztfaseId;
    }
    public BigDecimal getUztcitaId() {
        return this.uztcitaId;
    }
    
    public void setUztcitaId(BigDecimal uztcitaId) {
        this.uztcitaId = uztcitaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztcitaId) ) return false;
		 UztcitaId castOther = ( UztcitaId ) other; 
         
		 return ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) )
 && ( (this.getUztfaseId()==castOther.getUztfaseId()) || ( this.getUztfaseId()!=null && castOther.getUztfaseId()!=null && this.getUztfaseId().equals(castOther.getUztfaseId()) ) )
 && ( (this.getUztcitaId()==castOther.getUztcitaId()) || ( this.getUztcitaId()!=null && castOther.getUztcitaId()!=null && this.getUztcitaId().equals(castOther.getUztcitaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         result = 37 * result + ( getUztfaseId() == null ? 0 : this.getUztfaseId().hashCode() );
         result = 37 * result + ( getUztcitaId() == null ? 0 : this.getUztcitaId().hashCode() );
         return result;
   }   


}


