package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0



/**
 * Uztcomt generated by hbm2java
 */
public class Uztcomt  implements java.io.Serializable {


     private UztcomtId id;
     private Uztfase uztfase;
     private String uztcomtDescripcion;
     private String uztcomtFecha;

    public Uztcomt() {
        this.id = new UztcomtId();
        this.uztfase = new Uztfase();
    }

	
    public Uztcomt(UztcomtId id, Uztfase uztfase) {
        this.id = id;
        this.uztfase = uztfase;
    }
    public Uztcomt(UztcomtId id, Uztfase uztfase, String uztcomtDescripcion, String uztcomtFecha) {
       this.id = id;
       this.uztfase = uztfase;
       this.uztcomtDescripcion = uztcomtDescripcion;
       this.uztcomtFecha = uztcomtFecha;
    }
   
    public UztcomtId getId() {
        return this.id;
    }
    
    public void setId(UztcomtId id) {
        this.id = id;
    }
    public Uztfase getUztfase() {
        return this.uztfase;
    }
    
    public void setUztfase(Uztfase uztfase) {
        this.uztfase = uztfase;
    }
    public String getUztcomtDescripcion() {
        return this.uztcomtDescripcion;
    }
    
    public void setUztcomtDescripcion(String uztcomtDescripcion) {
        this.uztcomtDescripcion = uztcomtDescripcion;
    }
    public String getUztcomtFecha() {
        return this.uztcomtFecha;
    }
    
    public void setUztcomtFecha(String uztcomtFecha) {
        this.uztcomtFecha = uztcomtFecha;
    }




}


