package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Uztcita generated by hbm2java
 */
public class Uztcita  implements java.io.Serializable {


     private UztcitaId id;
     private Uztfase uztfase;
     private String uztcitaSala;
     private String uztcitaFecha;
     private BigDecimal uztcitaFlag;

    public Uztcita() {
    }

	
    public Uztcita(UztcitaId id, Uztfase uztfase) {
        this.id = id;
        this.uztfase = uztfase;
    }
    public Uztcita(UztcitaId id, Uztfase uztfase, String uztcitaSala, String uztcitaFecha, BigDecimal uztcitaFlag) {
       this.id = id;
       this.uztfase = uztfase;
       this.uztcitaSala = uztcitaSala;
       this.uztcitaFecha = uztcitaFecha;
       this.uztcitaFlag = uztcitaFlag;
    }
   
    public UztcitaId getId() {
        return this.id;
    }
    
    public void setId(UztcitaId id) {
        this.id = id;
    }
    public Uztfase getUztfase() {
        return this.uztfase;
    }
    
    public void setUztfase(Uztfase uztfase) {
        this.uztfase = uztfase;
    }
    public String getUztcitaSala() {
        return this.uztcitaSala;
    }
    
    public void setUztcitaSala(String uztcitaSala) {
        this.uztcitaSala = uztcitaSala;
    }
    public String getUztcitaFecha() {
        return this.uztcitaFecha;
    }
    
    public void setUztcitaFecha(String uztcitaFecha) {
        this.uztcitaFecha = uztcitaFecha;
    }
    public BigDecimal getUztcitaFlag() {
        return this.uztcitaFlag;
    }
    
    public void setUztcitaFlag(BigDecimal uztcitaFlag) {
        this.uztcitaFlag = uztcitaFlag;
    }




}


