package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztcomtId generated by hbm2java
 */
public class UztcomtId  implements java.io.Serializable {


     private BigDecimal uztcasoId;
     private BigDecimal uztfaseId;
     private BigDecimal uztcomtId;

    public UztcomtId() {
        this.uztcasoId = new BigDecimal(BigInteger.ONE);
        this.uztcomtId = new BigDecimal(BigInteger.ONE);
        this.uztfaseId = new BigDecimal(BigInteger.ONE);
    }

    public UztcomtId(BigDecimal uztcasoId, BigDecimal uztfaseId, BigDecimal uztcomtId) {
       this.uztcasoId = uztcasoId;
       this.uztfaseId = uztfaseId;
       this.uztcomtId = uztcomtId;
    }
   
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }
    public BigDecimal getUztfaseId() {
        return this.uztfaseId;
    }
    
    public void setUztfaseId(BigDecimal uztfaseId) {
        this.uztfaseId = uztfaseId;
    }
    public BigDecimal getUztcomtId() {
        return this.uztcomtId;
    }
    
    public void setUztcomtId(BigDecimal uztcomtId) {
        this.uztcomtId = uztcomtId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztcomtId) ) return false;
		 UztcomtId castOther = ( UztcomtId ) other; 
         
		 return ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) )
 && ( (this.getUztfaseId()==castOther.getUztfaseId()) || ( this.getUztfaseId()!=null && castOther.getUztfaseId()!=null && this.getUztfaseId().equals(castOther.getUztfaseId()) ) )
 && ( (this.getUztcomtId()==castOther.getUztcomtId()) || ( this.getUztcomtId()!=null && castOther.getUztcomtId()!=null && this.getUztcomtId().equals(castOther.getUztcomtId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         result = 37 * result + ( getUztfaseId() == null ? 0 : this.getUztfaseId().hashCode() );
         result = 37 * result + ( getUztcomtId() == null ? 0 : this.getUztcomtId().hashCode() );
         return result;
   }   


}


