package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztdocsId generated by hbm2java
 */
public class UztdocsId  implements java.io.Serializable {


     private BigDecimal uztcasoId;
     private BigDecimal uztfaseId;
     private BigDecimal uztdocsId;

    public UztdocsId() {
        this.uztcasoId = new BigDecimal(BigInteger.ONE);
        this.uztdocsId = new BigDecimal(BigInteger.ONE);
        this.uztfaseId = new BigDecimal(BigInteger.ONE);
    }

    public UztdocsId(BigDecimal uztcasoId, BigDecimal uztfaseId, BigDecimal uztdocsId) {
       this.uztcasoId = uztcasoId;
       this.uztfaseId = uztfaseId;
       this.uztdocsId = uztdocsId;
    }
   
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }
    public BigDecimal getUztfaseId() {
        return this.uztfaseId;
    }
    
    public void setUztfaseId(BigDecimal uztfaseId) {
        this.uztfaseId = uztfaseId;
    }
    public BigDecimal getUztdocsId() {
        return this.uztdocsId;
    }
    
    public void setUztdocsId(BigDecimal uztdocsId) {
        this.uztdocsId = uztdocsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztdocsId) ) return false;
		 UztdocsId castOther = ( UztdocsId ) other; 
         
		 return ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) )
 && ( (this.getUztfaseId()==castOther.getUztfaseId()) || ( this.getUztfaseId()!=null && castOther.getUztfaseId()!=null && this.getUztfaseId().equals(castOther.getUztfaseId()) ) )
 && ( (this.getUztdocsId()==castOther.getUztdocsId()) || ( this.getUztdocsId()!=null && castOther.getUztdocsId()!=null && this.getUztdocsId().equals(castOther.getUztdocsId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         result = 37 * result + ( getUztfaseId() == null ? 0 : this.getUztfaseId().hashCode() );
         result = 37 * result + ( getUztdocsId() == null ? 0 : this.getUztdocsId().hashCode() );
         return result;
   }   


}


