package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.sql.Blob;

/**
 * Uztdocs generated by hbm2java
 */
public class Uztdocs  implements java.io.Serializable {


     private UztdocsId id;
     private Uztfase uztfase;
     private String uztdocsCasilla;
     private String uztdocsFecha;
     private String uztdocsCompromiso;
     private Blob uztdocsArchivo;

    public Uztdocs() {
        this.id = new UztdocsId();
        this.uztfase = new Uztfase();
    }

	
    public Uztdocs(UztdocsId id, Uztfase uztfase) {
        this.id = id;
        this.uztfase = uztfase;
    }
    public Uztdocs(UztdocsId id, Uztfase uztfase, String uztdocsCasilla, String uztdocsFecha, String uztdocsCompromiso, Blob uztdocsArchivo) {
       this.id = id;
       this.uztfase = uztfase;
       this.uztdocsCasilla = uztdocsCasilla;
       this.uztdocsFecha = uztdocsFecha;
       this.uztdocsCompromiso = uztdocsCompromiso;
       this.uztdocsArchivo = uztdocsArchivo;
    }
   
    public UztdocsId getId() {
        return this.id;
    }
    
    public void setId(UztdocsId id) {
        this.id = id;
    }
    public Uztfase getUztfase() {
        return this.uztfase;
    }
    
    public void setUztfase(Uztfase uztfase) {
        this.uztfase = uztfase;
    }
    public String getUztdocsCasilla() {
        return this.uztdocsCasilla;
    }
    
    public void setUztdocsCasilla(String uztdocsCasilla) {
        this.uztdocsCasilla = uztdocsCasilla;
    }
    public String getUztdocsFecha() {
        return this.uztdocsFecha;
    }
    
    public void setUztdocsFecha(String uztdocsFecha) {
        this.uztdocsFecha = uztdocsFecha;
    }
    public String getUztdocsCompromiso() {
        return this.uztdocsCompromiso;
    }
    
    public void setUztdocsCompromiso(String uztdocsCompromiso) {
        this.uztdocsCompromiso = uztdocsCompromiso;
    }
    public Blob getUztdocsArchivo() {
        return this.uztdocsArchivo;
    }
    
    public void setUztdocsArchivo(Blob uztdocsArchivo) {
        this.uztdocsArchivo = uztdocsArchivo;
    }




}


