package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztfuncionario generated by hbm2java
 */
public class Uztfuncionario  implements java.io.Serializable {


     private BigDecimal uztfuncionarioId;
     private BigDecimal uztfuncionarioFlag;
     private String uztfuncionarioNombres;
     private String uztfuncionarioApellidos;
     private String uztfuncionarioCedula;
     private String uztfuncionarioEmail;
     private String uztfuncionarioMovil;
     private Set uztrols = new HashSet(0);
     private Set uztasignars = new HashSet(0);
     private Set uztinvolFfs = new HashSet(0);

    public Uztfuncionario() {
        this.uztfuncionarioId = new BigDecimal(BigInteger.ZERO);
        this.uztfuncionarioFlag = new BigDecimal(BigInteger.ZERO); // desactivado
    }

	
    public Uztfuncionario(BigDecimal uztfuncionarioId) {
        this.uztfuncionarioId = uztfuncionarioId;
    }
    public Uztfuncionario(BigDecimal uztfuncionarioId, BigDecimal uztfuncionarioFlag, String uztfuncionarioNombres, String uztfuncionarioApellidos, String uztfuncionarioCedula, String uztfuncionarioEmail, String uztfuncionarioMovil, Set uztrols, Set uztasignars, Set uztinvolFfs) {
       this.uztfuncionarioId = uztfuncionarioId;
       this.uztfuncionarioFlag = uztfuncionarioFlag;
       this.uztfuncionarioNombres = uztfuncionarioNombres;
       this.uztfuncionarioApellidos = uztfuncionarioApellidos;
       this.uztfuncionarioCedula = uztfuncionarioCedula;
       this.uztfuncionarioEmail = uztfuncionarioEmail;
       this.uztfuncionarioMovil = uztfuncionarioMovil;
       this.uztrols = uztrols;
       this.uztasignars = uztasignars;
       this.uztinvolFfs = uztinvolFfs;
    }
   
    public BigDecimal getUztfuncionarioId() {
        return this.uztfuncionarioId;
    }
    
    public void setUztfuncionarioId(BigDecimal uztfuncionarioId) {
        this.uztfuncionarioId = uztfuncionarioId;
    }
    public BigDecimal getUztfuncionarioFlag() {
        return this.uztfuncionarioFlag;
    }
    
    public void setUztfuncionarioFlag(BigDecimal uztfuncionarioFlag) {
        this.uztfuncionarioFlag = uztfuncionarioFlag;
    }
    public String getUztfuncionarioNombres() {
        return this.uztfuncionarioNombres;
    }
    
    public void setUztfuncionarioNombres(String uztfuncionarioNombres) {
        this.uztfuncionarioNombres = uztfuncionarioNombres;
    }
    public String getUztfuncionarioApellidos() {
        return this.uztfuncionarioApellidos;
    }
    
    public void setUztfuncionarioApellidos(String uztfuncionarioApellidos) {
        this.uztfuncionarioApellidos = uztfuncionarioApellidos;
    }
    public String getUztfuncionarioCedula() {
        return this.uztfuncionarioCedula;
    }
    
    public void setUztfuncionarioCedula(String uztfuncionarioCedula) {
        this.uztfuncionarioCedula = uztfuncionarioCedula;
    }
    public String getUztfuncionarioEmail() {
        return this.uztfuncionarioEmail;
    }
    
    public void setUztfuncionarioEmail(String uztfuncionarioEmail) {
        this.uztfuncionarioEmail = uztfuncionarioEmail;
    }
    public String getUztfuncionarioMovil() {
        return this.uztfuncionarioMovil;
    }
    
    public void setUztfuncionarioMovil(String uztfuncionarioMovil) {
        this.uztfuncionarioMovil = uztfuncionarioMovil;
    }
    public Set getUztrols() {
        return this.uztrols;
    }
    
    public void setUztrols(Set uztrols) {
        this.uztrols = uztrols;
    }
    public Set getUztasignars() {
        return this.uztasignars;
    }
    
    public void setUztasignars(Set uztasignars) {
        this.uztasignars = uztasignars;
    }
    public Set getUztinvolFfs() {
        return this.uztinvolFfs;
    }
    
    public void setUztinvolFfs(Set uztinvolFfs) {
        this.uztinvolFfs = uztinvolFfs;
    }




}


