package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztinvolCaId generated by hbm2java
 */
public class UztinvolCaId  implements java.io.Serializable {


     private BigDecimal uztactorId;
     private BigDecimal uztcasoId;

    public UztinvolCaId() {
        this.uztactorId = new BigDecimal(BigInteger.ONE);
        this.uztcasoId = new BigDecimal(BigInteger.ONE);
    }

    public UztinvolCaId(BigDecimal uztactorId, BigDecimal uztcasoId) {
       this.uztactorId = uztactorId;
       this.uztcasoId = uztcasoId;
    }
   
    public BigDecimal getUztactorId() {
        return this.uztactorId;
    }
    
    public void setUztactorId(BigDecimal uztactorId) {
        this.uztactorId = uztactorId;
    }
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztinvolCaId) ) return false;
		 UztinvolCaId castOther = ( UztinvolCaId ) other; 
         
		 return ( (this.getUztactorId()==castOther.getUztactorId()) || ( this.getUztactorId()!=null && castOther.getUztactorId()!=null && this.getUztactorId().equals(castOther.getUztactorId()) ) )
 && ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztactorId() == null ? 0 : this.getUztactorId().hashCode() );
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         return result;
   }   


}


