package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztinvolFfId generated by hbm2java
 */
public class UztinvolFfId  implements java.io.Serializable {


     private BigDecimal uztcasoId;
     private BigDecimal uztfuncionarioId;
     private BigDecimal uztfaseId;

    public UztinvolFfId() {
        this.uztcasoId = new BigDecimal(BigInteger.ONE);
        this.uztfaseId = new BigDecimal(BigInteger.ONE);
        this.uztfuncionarioId = new BigDecimal(BigInteger.ONE);
    }

    public UztinvolFfId(BigDecimal uztcasoId, BigDecimal uztfuncionarioId, BigDecimal uztfaseId) {
       this.uztcasoId = uztcasoId;
       this.uztfuncionarioId = uztfuncionarioId;
       this.uztfaseId = uztfaseId;
    }
   
    public BigDecimal getUztcasoId() {
        return this.uztcasoId;
    }
    
    public void setUztcasoId(BigDecimal uztcasoId) {
        this.uztcasoId = uztcasoId;
    }
    public BigDecimal getUztfuncionarioId() {
        return this.uztfuncionarioId;
    }
    
    public void setUztfuncionarioId(BigDecimal uztfuncionarioId) {
        this.uztfuncionarioId = uztfuncionarioId;
    }
    public BigDecimal getUztfaseId() {
        return this.uztfaseId;
    }
    
    public void setUztfaseId(BigDecimal uztfaseId) {
        this.uztfaseId = uztfaseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztinvolFfId) ) return false;
		 UztinvolFfId castOther = ( UztinvolFfId ) other; 
         
		 return ( (this.getUztcasoId()==castOther.getUztcasoId()) || ( this.getUztcasoId()!=null && castOther.getUztcasoId()!=null && this.getUztcasoId().equals(castOther.getUztcasoId()) ) )
 && ( (this.getUztfuncionarioId()==castOther.getUztfuncionarioId()) || ( this.getUztfuncionarioId()!=null && castOther.getUztfuncionarioId()!=null && this.getUztfuncionarioId().equals(castOther.getUztfuncionarioId()) ) )
 && ( (this.getUztfaseId()==castOther.getUztfaseId()) || ( this.getUztfaseId()!=null && castOther.getUztfaseId()!=null && this.getUztfaseId().equals(castOther.getUztfaseId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztcasoId() == null ? 0 : this.getUztcasoId().hashCode() );
         result = 37 * result + ( getUztfuncionarioId() == null ? 0 : this.getUztfuncionarioId().hashCode() );
         result = 37 * result + ( getUztfaseId() == null ? 0 : this.getUztfaseId().hashCode() );
         return result;
   }   


}


