package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0



/**
 * UztinvolCa generated by hbm2java
 */
public class UztinvolCa  implements java.io.Serializable {


     private UztinvolCaId id;
     private Uztcaso uztcaso;
     private Uztactor uztactor;
     private String uztinvolCa;

    public UztinvolCa() {
        this.id = new UztinvolCaId();
        this.uztactor = new Uztactor();
        this.uztcaso = new Uztcaso();
    }

	
    public UztinvolCa(UztinvolCaId id, Uztcaso uztcaso, Uztactor uztactor) {
        this.id = id;
        this.uztcaso = uztcaso;
        this.uztactor = uztactor;
    }
    public UztinvolCa(UztinvolCaId id, Uztcaso uztcaso, Uztactor uztactor, String uztinvolCa) {
       this.id = id;
       this.uztcaso = uztcaso;
       this.uztactor = uztactor;
       this.uztinvolCa = uztinvolCa;
    }
   
    public UztinvolCaId getId() {
        return this.id;
    }
    
    public void setId(UztinvolCaId id) {
        this.id = id;
    }
    public Uztcaso getUztcaso() {
        return this.uztcaso;
    }
    
    public void setUztcaso(Uztcaso uztcaso) {
        this.uztcaso = uztcaso;
    }
    public Uztactor getUztactor() {
        return this.uztactor;
    }
    
    public void setUztactor(Uztactor uztactor) {
        this.uztactor = uztactor;
    }
    public String getUztinvolCa() {
        return this.uztinvolCa;
    }
    
    public void setUztinvolCa(String uztinvolCa) {
        this.uztinvolCa = uztinvolCa;
    }




}


