package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0



/**
 * UztinvolFf generated by hbm2java
 */
public class UztinvolFf  implements java.io.Serializable {


     private UztinvolFfId id;
     private Uztfase uztfase;
     private Uztfuncionario uztfuncionario;
     private String uztinvolFfFechaIn;
     private String uztinvolFfFechaOut;

    public UztinvolFf() {
        this.id = new UztinvolFfId();
        this.uztfase = new Uztfase();
        this.uztfuncionario = new Uztfuncionario();
    }

	
    public UztinvolFf(UztinvolFfId id, Uztfase uztfase, Uztfuncionario uztfuncionario) {
        this.id = id;
        this.uztfase = uztfase;
        this.uztfuncionario = uztfuncionario;
    }
    public UztinvolFf(UztinvolFfId id, Uztfase uztfase, Uztfuncionario uztfuncionario, String uztinvolFfFechaIn, String uztinvolFfFechaOut) {
       this.id = id;
       this.uztfase = uztfase;
       this.uztfuncionario = uztfuncionario;
       this.uztinvolFfFechaIn = uztinvolFfFechaIn;
       this.uztinvolFfFechaOut = uztinvolFfFechaOut;
    }
   
    public UztinvolFfId getId() {
        return this.id;
    }
    
    public void setId(UztinvolFfId id) {
        this.id = id;
    }
    public Uztfase getUztfase() {
        return this.uztfase;
    }
    
    public void setUztfase(Uztfase uztfase) {
        this.uztfase = uztfase;
    }
    public Uztfuncionario getUztfuncionario() {
        return this.uztfuncionario;
    }
    
    public void setUztfuncionario(Uztfuncionario uztfuncionario) {
        this.uztfuncionario = uztfuncionario;
    }
    public String getUztinvolFfFechaIn() {
        return this.uztinvolFfFechaIn;
    }
    
    public void setUztinvolFfFechaIn(String uztinvolFfFechaIn) {
        this.uztinvolFfFechaIn = uztinvolFfFechaIn;
    }
    public String getUztinvolFfFechaOut() {
        return this.uztinvolFfFechaOut;
    }
    
    public void setUztinvolFfFechaOut(String uztinvolFfFechaOut) {
        this.uztinvolFfFechaOut = uztinvolFfFechaOut;
    }




}


