package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * UztjudiId generated by hbm2java
 */
public class UztjudiId  implements java.io.Serializable {


     private BigDecimal uztmateriaId;
     private BigDecimal uztjudiId;

    public UztjudiId() {
    }

    public UztjudiId(BigDecimal uztmateriaId, BigDecimal uztjudiId) {
       this.uztmateriaId = uztmateriaId;
       this.uztjudiId = uztjudiId;
    }
   
    public BigDecimal getUztmateriaId() {
        return this.uztmateriaId;
    }
    
    public void setUztmateriaId(BigDecimal uztmateriaId) {
        this.uztmateriaId = uztmateriaId;
    }
    public BigDecimal getUztjudiId() {
        return this.uztjudiId;
    }
    
    public void setUztjudiId(BigDecimal uztjudiId) {
        this.uztjudiId = uztjudiId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztjudiId) ) return false;
		 UztjudiId castOther = ( UztjudiId ) other; 
         
		 return ( (this.getUztmateriaId()==castOther.getUztmateriaId()) || ( this.getUztmateriaId()!=null && castOther.getUztmateriaId()!=null && this.getUztmateriaId().equals(castOther.getUztmateriaId()) ) )
 && ( (this.getUztjudiId()==castOther.getUztjudiId()) || ( this.getUztjudiId()!=null && castOther.getUztjudiId()!=null && this.getUztjudiId().equals(castOther.getUztjudiId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztmateriaId() == null ? 0 : this.getUztmateriaId().hashCode() );
         result = 37 * result + ( getUztjudiId() == null ? 0 : this.getUztjudiId().hashCode() );
         return result;
   }   


}


