package procuradoria.map;
// Generated Jan 7, 2016 1:07:49 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Uztjudi generated by hbm2java
 */
public class Uztjudi  implements java.io.Serializable {


     private UztjudiId id;
     private Uztmateria uztmateria;
     private String uztjudiDescripcion;
     private Set uztcasos = new HashSet(0);

    public Uztjudi() {
        this.uztmateria = new Uztmateria();
    }

	
    public Uztjudi(UztjudiId id, Uztmateria uztmateria) {
        this.id = id;
        this.uztmateria = uztmateria;
    }
    public Uztjudi(UztjudiId id, Uztmateria uztmateria, String uztjudiDescripcion, Set uztcasos) {
       this.id = id;
       this.uztmateria = uztmateria;
       this.uztjudiDescripcion = uztjudiDescripcion;
       this.uztcasos = uztcasos;
    }
   
    public UztjudiId getId() {
        return this.id;
    }
    
    public void setId(UztjudiId id) {
        this.id = id;
    }
    public Uztmateria getUztmateria() {
        return this.uztmateria;
    }
    
    public void setUztmateria(Uztmateria uztmateria) {
        this.uztmateria = uztmateria;
    }
    public String getUztjudiDescripcion() {
        return this.uztjudiDescripcion;
    }
    
    public void setUztjudiDescripcion(String uztjudiDescripcion) {
        this.uztjudiDescripcion = uztjudiDescripcion;
    }
    public Set getUztcasos() {
        return this.uztcasos;
    }
    
    public void setUztcasos(Set uztcasos) {
        this.uztcasos = uztcasos;
    }




}


