package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Uztmateria generated by hbm2java
 */
public class Uztmateria  implements java.io.Serializable {


     private BigDecimal uztmateriaId;
     private String uztmateriaDescripcion;
     private Set uztjudis = new HashSet(0);

    public Uztmateria() {
        this.uztmateriaId = new BigDecimal(BigInteger.ONE);
    }

	
    public Uztmateria(BigDecimal uztmateriaId) {
        this.uztmateriaId = uztmateriaId;
    }
    public Uztmateria(BigDecimal uztmateriaId, String uztmateriaDescripcion, Set uztjudis) {
       this.uztmateriaId = uztmateriaId;
       this.uztmateriaDescripcion = uztmateriaDescripcion;
       this.uztjudis = uztjudis;
    }
   
    public BigDecimal getUztmateriaId() {
        return this.uztmateriaId;
    }
    
    public void setUztmateriaId(BigDecimal uztmateriaId) {
        this.uztmateriaId = uztmateriaId;
    }
    public String getUztmateriaDescripcion() {
        return this.uztmateriaDescripcion;
    }
    
    public void setUztmateriaDescripcion(String uztmateriaDescripcion) {
        this.uztmateriaDescripcion = uztmateriaDescripcion;
    }
    public Set getUztjudis() {
        return this.uztjudis;
    }
    
    public void setUztjudis(Set uztjudis) {
        this.uztjudis = uztjudis;
    }




}


