package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * UztrolId generated by hbm2java
 */
public class UztrolId  implements java.io.Serializable {


     private BigDecimal uztfuncionarioId;
     private BigDecimal uzttiporolId;
     private BigDecimal uztrolId;

    public UztrolId() {
        this.uztfuncionarioId = new BigDecimal(BigInteger.ONE);
        this.uztrolId = new BigDecimal(BigInteger.ONE);
        this.uzttiporolId = new BigDecimal(BigInteger.ONE);
    }

    public UztrolId(BigDecimal uztfuncionarioId, BigDecimal uzttiporolId, BigDecimal uztrolId) {
       this.uztfuncionarioId = uztfuncionarioId;
       this.uzttiporolId = uzttiporolId;
       this.uztrolId = uztrolId;
    }
   
    public BigDecimal getUztfuncionarioId() {
        return this.uztfuncionarioId;
    }
    
    public void setUztfuncionarioId(BigDecimal uztfuncionarioId) {
        this.uztfuncionarioId = uztfuncionarioId;
    }
    public BigDecimal getUzttiporolId() {
        return this.uzttiporolId;
    }
    
    public void setUzttiporolId(BigDecimal uzttiporolId) {
        this.uzttiporolId = uzttiporolId;
    }
    public BigDecimal getUztrolId() {
        return this.uztrolId;
    }
    
    public void setUztrolId(BigDecimal uztrolId) {
        this.uztrolId = uztrolId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UztrolId) ) return false;
		 UztrolId castOther = ( UztrolId ) other; 
         
		 return ( (this.getUztfuncionarioId()==castOther.getUztfuncionarioId()) || ( this.getUztfuncionarioId()!=null && castOther.getUztfuncionarioId()!=null && this.getUztfuncionarioId().equals(castOther.getUztfuncionarioId()) ) )
 && ( (this.getUzttiporolId()==castOther.getUzttiporolId()) || ( this.getUzttiporolId()!=null && castOther.getUzttiporolId()!=null && this.getUzttiporolId().equals(castOther.getUzttiporolId()) ) )
 && ( (this.getUztrolId()==castOther.getUztrolId()) || ( this.getUztrolId()!=null && castOther.getUztrolId()!=null && this.getUztrolId().equals(castOther.getUztrolId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUztfuncionarioId() == null ? 0 : this.getUztfuncionarioId().hashCode() );
         result = 37 * result + ( getUzttiporolId() == null ? 0 : this.getUzttiporolId().hashCode() );
         result = 37 * result + ( getUztrolId() == null ? 0 : this.getUztrolId().hashCode() );
         return result;
   }   


}


