package procuradoria.map;
// Generated Feb 2, 2016 9:54:14 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * Uzttiporol generated by hbm2java
 */
public class Uzttiporol  implements java.io.Serializable {


     private BigDecimal uzttiporolId;
     private String uzttiporolDescripcion;
     private Set uztrols = new HashSet(0);

    public Uzttiporol() {
        this.uzttiporolId = new BigDecimal(BigInteger.ONE);
    }

	
    public Uzttiporol(BigDecimal uzttiporolId) {
        this.uzttiporolId = uzttiporolId;
    }
    public Uzttiporol(BigDecimal uzttiporolId, String uzttiporolDescripcion, Set uztrols) {
       this.uzttiporolId = uzttiporolId;
       this.uzttiporolDescripcion = uzttiporolDescripcion;
       this.uztrols = uztrols;
    }
   
    public BigDecimal getUzttiporolId() {
        return this.uzttiporolId;
    }
    
    public void setUzttiporolId(BigDecimal uzttiporolId) {
        this.uzttiporolId = uzttiporolId;
    }
    public String getUzttiporolDescripcion() {
        return this.uzttiporolDescripcion;
    }
    
    public void setUzttiporolDescripcion(String uzttiporolDescripcion) {
        this.uzttiporolDescripcion = uzttiporolDescripcion;
    }
    public Set getUztrols() {
        return this.uztrols;
    }
    
    public void setUztrols(Set uztrols) {
        this.uztrols = uztrols;
    }




}


